### ISSUE TITLE
"No Response" from Alarm System accessory when system is armed

### ISSUE THREAD

**Issue by twangus** [aficustree/homebridge-alarmdecoder-platform#17] opened 2020-05-07 18:12 UTC
I mentioned this in my comments on another issue, but it seems like the problem I'm seeing is different and more reproducible in my set up, so I'm opening a new issue.

Basically, the accessories all seem to work fine when system is disarmed.  I can use the Alarm System accessory to arm the system to "Home," which properly arms my Honeywell system to "Stay."  But once the system is armed, the Alarm System accessory becomes unresponsive.  This isn't immediately obvious in the Home app interface (which seems to cache the state), but eventually the Alarm System accessory will show "No Response" and can't display or set the state (and it will do this behavior right away if I force quit and restart the Home app).  If I disarm the system (e.g., using a manual keypad or the Web App), the Alarm System accessory in HomeKit becomes responsive again and displays the correct disarmed state.

I've got a Honeywell system with a very basic plugin config (basically just the Honeywell Example config with my info replaced and without the "panic key" or "switches" options).  The Alarmdecoder Web App is up-to-date and functioning fine.  I've explicitly identified the IP addresses and ports in the config for the plugin and web app notifications to try to rule out any DNS issues.  And it looks from the logs like the plugin is communicating correctly with the Alarmdecoder Web App API even when the Alarm System accessory is showing up as not responsive.

I've tried on two separate clean homebridge installations (running on different machines), and I get the same behavior on both.

I ran one in debug mode to see if I could get any information.  When disarmed, the plugin can successfully get the state for all of the sensor characteristics, including the "Security System Target State" and "Security System Current State" (with value 3 for disarmed):

	[5/6/2020, 8:32:35 PM] [Alarm System] {"last_message_received":"[10000001000000003A--],008,[f70600ff1008001c08020000000000],\"****DISARMED****  Ready to Arm  \"","panel_alarming":false,"panel_armed":false,"panel_armed_stay":false,"panel_battery_trouble":false,"panel_bypassed":{},"panel_chime":false,"panel_entry_delay_off":false,"panel_exit":false,"panel_fire_detected":false,"panel_panicked":false,"panel_perimeter_only":false,"panel_powered":true,"panel_ready":true,"panel_relay_status":[],"panel_type":"ADEMCO","panel_zones_faulted":[]}
		Accessory [Dev Homebridge] Got Characteristic "Contact Sensor State" value: 0 +34ms
	[5/6/2020, 8:32:35 PM] [Alarm System] {"last_message_received":"[10000001000000003A--],008,[f70600ff1008001c08020000000000],\"****DISARMED****  Ready to Arm  \"","panel_alarming":false,"panel_armed":false,"panel_armed_stay":false,"panel_battery_trouble":false,"panel_bypassed":{},"panel_chime":false,"panel_entry_delay_off":false,"panel_exit":false,"panel_fire_detected":false,"panel_panicked":false,"panel_perimeter_only":false,"panel_powered":true,"panel_ready":true,"panel_relay_status":[],"panel_type":"ADEMCO","panel_zones_faulted":[]}
		Accessory [Dev Homebridge] Got Characteristic "Security System Target State" value: 3 +34ms
	[5/6/2020, 8:32:35 PM] [Alarm System] {"last_message_received":"[10000001000000003A--],008,[f70600ff1008001c08020000000000],\"****DISARMED****  Ready to Arm  \"","panel_alarming":false,"panel_armed":false,"panel_armed_stay":false,"panel_battery_trouble":false,"panel_bypassed":{},"panel_chime":false,"panel_entry_delay_off":false,"panel_exit":false,"panel_fire_detected":false,"panel_panicked":false,"panel_perimeter_only":false,"panel_powered":true,"panel_ready":true,"panel_relay_status":[],"panel_type":"ADEMCO","panel_zones_faulted":[]}
		Accessory [Dev Homebridge] Got Characteristic "Security System Current State" value: 3 +33ms
	[5/6/2020, 8:32:35 PM] [Alarm System] {"last_message_received":"[10000001000000003A--],008,[f70600ff1008001c08020000000000],\"****DISARMED****  Ready to Arm  \"","panel_alarming":false,"panel_armed":false,"panel_armed_stay":false,"panel_battery_trouble":false,"panel_bypassed":{},"panel_chime":false,"panel_entry_delay_off":false,"panel_exit":false,"panel_fire_detected":false,"panel_panicked":false,"panel_perimeter_only":false,"panel_powered":true,"panel_ready":true,"panel_relay_status":[],"panel_type":"ADEMCO","panel_zones_faulted":[]}
		Accessory [Dev Homebridge] Got Characteristic "Contact Sensor State" value: 0 +35ms

When I arm the system to Home / Stay, the debug log shows that characteristic being set:

	Accessory [Dev Homebridge] Setting Characteristic "Security System Target State" to value 0 +0ms

That arms the system, which is reflected in the API messages:

	5/6/2020, 8:33:16 PM] [Alarm System] {"last_message_received":"[00110301000000003A--],008,[f70600f51008038c08020000000000],\"ARMED ***STAY***You may exit now\"","panel_alarming":false,"panel_armed":false,"panel_armed_stay":true,"panel_battery_trouble":false,"panel_bypassed":{},"panel_chime":false,"panel_entry_delay_off":false,"panel_exit":true,"panel_fire_detected":false,"panel_panicked":false,"panel_perimeter_only":false,"panel_powered":true,"panel_ready":false,"panel_relay_status":[],"panel_type":"ADEMCO","panel_zones_faulted":[]}

The next time HomeKit checks the status, the plugin seems to get all of the correct API responses from Web App.  It reports values for the individual sensors but for some reason it reports the "Security System Current State" and "Security System Target State" as "undefined" (when it should have value 0 for "stay"):

	[5/6/2020, 8:33:50 PM] [Alarm System] {"last_message_received":"[00110001000000003A--],008,[f70600ff1008008c08020000000000],\"ARMED ***STAY***You may exit now\"","panel_alarming":false,"panel_armed":false,"panel_armed_stay":true,"panel_battery_trouble":false,"panel_bypassed":{},"panel_chime":false,"panel_entry_delay_off":false,"panel_exit":true,"panel_fire_detected":false,"panel_panicked":false,"panel_perimeter_only":false,"panel_powered":true,"panel_ready":false,"panel_relay_status":[],"panel_type":"ADEMCO","panel_zones_faulted":[]}
		Accessory [Dev Homebridge] Got Characteristic "Motion Detected" value: false +35ms
	[5/6/2020, 8:33:50 PM] [Alarm System] {"last_message_received":"[00110001000000003A--],008,[f70600ff1008008c08020000000000],\"ARMED ***STAY***You may exit now\"","panel_alarming":false,"panel_armed":false,"panel_armed_stay":true,"panel_battery_trouble":false,"panel_bypassed":{},"panel_chime":false,"panel_entry_delay_off":false,"panel_exit":true,"panel_fire_detected":false,"panel_panicked":false,"panel_perimeter_only":false,"panel_powered":true,"panel_ready":false,"panel_relay_status":[],"panel_type":"ADEMCO","panel_zones_faulted":[]}
		Accessory [Dev Homebridge] Error getting value for Characteristic "Security System Current State": undefined +38ms
	[5/6/2020, 8:33:50 PM] [Alarm System] {"last_message_received":"[00110001000000003A--],008,[f70600ff1008008c08020000000000],\"ARMED ***STAY***You may exit now\"","panel_alarming":false,"panel_armed":false,"panel_armed_stay":true,"panel_battery_trouble":false,"panel_bypassed":{},"panel_chime":false,"panel_entry_delay_off":false,"panel_exit":true,"panel_fire_detected":false,"panel_panicked":false,"panel_perimeter_only":false,"panel_powered":true,"panel_ready":false,"panel_relay_status":[],"panel_type":"ADEMCO","panel_zones_faulted":[]}
		Accessory [Dev Homebridge] Error getting value for Characteristic "Security System Target State": undefined +37ms
	[5/6/2020, 8:33:50 PM] [Alarm System] {"last_message_received":"[00110001000000003A--],008,[f70600ff1008008c08020000000000],\"ARMED ***STAY***You may exit now\"","panel_alarming":false,"panel_armed":false,"panel_armed_stay":true,"panel_battery_trouble":false,"panel_bypassed":{},"panel_chime":false,"panel_entry_delay_off":false,"panel_exit":true,"panel_fire_detected":false,"panel_panicked":false,"panel_perimeter_only":false,"panel_powered":true,"panel_ready":false,"panel_relay_status":[],"panel_type":"ADEMCO","panel_zones_faulted":[]}
		Accessory [Dev Homebridge] Got Characteristic "Contact Sensor State" value: 0 +36ms

Any idea what could be going on?

**Comment by aficustree** [comment] 2020-05-10 18:37
lots of things have changed recently in home bridge. Can you pul the 'fix17' branch and run home bridge with...

`DEBUG=alarmdecoder homebridge -D .`

and see send me some of the debug traces when you're getting that behavior?

**Comment by aficustree** [comment] 2020-05-11 16:35
also pushed 3.1.6 to fix a bug with the old `identify` function, might try that in-case that's causing an impact of some form

**Comment by twangus** [comment] 2020-05-12 15:45
Thanks - the 3.1.6 fix doesn't seem to change this issue.

I pulled the fix17 branch and ran homebridge with that command, but I'm now seeing at lot less debug information in the homebridge output shown in the terminal.  For example, now it just says "alarmdecoder getting state for" each of the zones, but doesn't given any additional information about what is going on. 

I'm not really clear on how the debug logging works.  With those flags, it is sending the debug log info to a file instead of the terminal output?  If so, I'm not sure where to find it.  Any additional info would be appreciated.

**Comment by jondthompson** [comment] 2020-07-07 03:03
Is this a duplicate of my bug that is still open?  When the alarm system in HK is unresponsive, can you still successfully arm and disarm it via Siri although it gives you a warning that it might not work? I can with my bug.

**Comment by jondthompson** [comment] 2020-11-16 18:11
Digging into this deeper, this is indeed my bug as well (#15).  I've been troubleshooting it further and it occurs whether I use the keypad or homekit, but only when I use the <code>3 state, which is "Stay/Home/Night*". However, if I use <code>2 "away" on any device, it works perfectly. This resulted in my thinking that it was sporadic, when in reality I just hadn't found correlation with the states yet.

Anyhow, digging into it a bit more now that there's a bit more of a smoking gun.

*You have Honeywell using code '33' for "night" mode, and the ADEMCO manual says '7' is "Instant", which you attribute as night mode in your code, and '4' is actually "max" which is what the manual suggests at night. I think '33' is just putting it in the errored '3' state.

**Comment by jondthompson** [comment] 2020-11-19 22:35
Ok, my fork at least solves the "night" issue by changing the night mode from a unknown '33', which is interpreted as "3 -away" instead to "7 - Immediate". It cleared the issue up to just being about "3 - away"

**Comment by stuntman999** [comment] 2020-12-05 22:02
Hi, I just setup this homebridge plugin with an Interlogix panel and I think I'm having the same problem...  I found something that could maybe help...   If I Arm my system in the "Stay" mode, my Alarm System show as "No Response" in Homekit. But what I found is the Switch Update correctly, my "Stay" switch is turned on but the "Alarm System" show no response..  The Switch part sync ok even if I use my keypad....    It seem like a bug in the plugin for Stay mode and not related to the type of panel...  If I do same thing in Away mode everything is ok and the Alarm System + Switch sync correctly.

**Comment by jondthompson** [comment] 2020-12-17 17:55
I suspect it's related to HK using the term "Home" instead of "Stay", but I can't quite figure out how that matters in the code (nor should it, but this is what I suspect)

**Comment by djstiky** [comment] 2021-01-09 23:59
I'm having the same issue with my DSC panel. Stay is not working and sets it to away instead. I also get "No Response" when I set the alarm to stay via the keypad directly.
I restored my old SD card image which uses homebridge-alarmdecoder-platform v1.2.2 on Homebridge v0.4.43 and everything is back to normal. Not sure what I'm missing out on with newer versions.

**Comment by jondthompson** [comment] 2021-01-10 02:58
I’m working through this issue as it affects me directly, but am working on a different plugin right now as it seems to be a bug in the home bridge api more than it is in this plugin, and I have a workaround (I just use night mode rather than away) 

— 
Jon

**Comment by djstiky** [comment] 2021-01-10 17:11
Hoping this could be solved soon to avoid having 2 different machines with old / current Homebridge. Thanks guys.

**Comment by jondthompson** [comment] 2021-04-05 21:18
I'm not sure how, but this has been solved as of Alarmdecoder Webapp e179246, Library 8a1a917, running on a raspberry pi running Raspbian GNU/Linux Buster (10), NodeJS v12.22.0, and NPM v6.14.11. It is also running homebridge 1.3.4 and Homebridge Alarmdecoder Platform 3.1.6.  I'm guessing the bug was in Homebridge itself, as this seems to be the only thing that really has been updated since I tried to solve this the last time.

**Comment by jondthompson** [comment] 2021-04-19 20:45
Nevermind. I forgot the mode that caused this issue.. It's "Home"

**Comment by jondthompson** [comment] 2021-04-20 00:04
Pull request into fix17 submitted.

**Comment by djstiky** [comment] 2021-04-20 00:43
Is there any hope for the “home” or “stay” function to be fixed?

**Comment by jondthompson** [comment] 2021-04-20 01:07
Yes, there's a pull request with the fix. @aficustree please get it merged asap.

**Comment by aficustree** [comment] 2021-04-20 02:42
just merged

**Closed as completed by aficustree** 2021-04-20 02:42 UTC
